# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Momentum < Formula
  desc "Lightweight CLI for managing Flux agents"
  homepage "https://github.com/stephenmfriend/momentum"
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stephenmfriend/momentum/releases/download/v1.0.5/momentum_1.0.5_darwin_amd64.tar.gz"
      sha256 "4104faa4df23ffaa61e6c0dc60729a2105ef78f1f364ed763498292072d7b7cf"

      def install
        bin.install "momentum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stephenmfriend/momentum/releases/download/v1.0.5/momentum_1.0.5_darwin_arm64.tar.gz"
      sha256 "adaf2bf031eccfc32ea1df0e87a5184c4be820f479fa69f2a94c60b0709d0628"

      def install
        bin.install "momentum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stephenmfriend/momentum/releases/download/v1.0.5/momentum_1.0.5_linux_amd64.tar.gz"
      sha256 "a8f41ad88ad37ae57ef47c893dd53c7ce73368dd2fe814e7ae7186a4bcfdb2ed"
      def install
        bin.install "momentum"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stephenmfriend/momentum/releases/download/v1.0.5/momentum_1.0.5_linux_arm64.tar.gz"
      sha256 "3731b2e6cda406bb6a6f6c2fa12713bef20856780964d3862ee4d3bed5c60684"
      def install
        bin.install "momentum"
      end
    end
  end

  test do
    system "#{bin}/momentum", "--version"
  end
end
